---

- name: "APPLY | {{ cis_code }} - reboot the machine"
  reboot:
    msg: "Reboot initiated by CIS {{ cis_code }}."
    reboot_timeout: 600
  register: cis_reboot_tmp
  tags:
    - apply

- name: "APPLY | {{ cis_code }} - set reboot fact."
  set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_reboot":"{{ cis_reboot_tmp }}"}
  tags:
    - apply

- name: "APPLY | {{ cis_code }} - print reboot status"
  debug:
    var: cis_reboot_tmp
  tags:
    - apply
    - debug

...
