---

# When the script returns non zero rc or produces stderr then apply fails.

- name: "APPLY | {{ cis_code }} - print script name"
  debug:
    var: cis_script
  tags:
    - apply
    - debug

- name: "APPLY | {{ cis_code }} - copy apply script"
  copy:
    src: "{{ cis_script }}"
    dest: "/root/cis-{{ cis_code }}-apply.sh"
    owner: root
    group: root
    mode: 'u=rwx,g=,o='
    backup: 'no'
    force: 'yes'
    remote_src: 'no'
  tags:
    - apply

- name: "APPLY | {{ cis_code }} - execute apply script"
  command: "/root/cis-{{ cis_code }}-apply.sh"
  failed_when: >-
    cis_apply_tmp.rc!=0 or
    cis_apply_tmp.stderr|length>0
  register: cis_apply_tmp
  tags:
    - apply

- name: "APPLY | {{ cis_code }} - clean apply script"
  file:
    path: "/root/cis-{{ cis_code }}-apply.sh"
    state: absent
  tags:
    - apply

- name: "APPLY | {{ cis_code }} - set apply fact"
  set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
  tags:
    - apply

- name: "APPLY | {{ cis_code }} - print script result"
  debug:
    var: cis_apply_tmp
  tags:
    - apply
    - debug

...
