---

- name: "APPLY | {{ cis_code }} - update parameter"
  sysctl:
    name: "{{ param }}"
    value: "{{ value }}"
    reload: 'yes'
    sysctl_set: 'yes'
    state: present
  register: cis_apply_tmp
  tags:
    - apply

- name: "APPLY | {{ cis_code }} - set apply fact"
  set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
  tags:
    - apply

  # Parameter should be here anyway
- name: "POST | {{ cis_code }} - get current info"
  shell: |
    sysctl {{ param }}
    grep -E "^{{ param }}" /etc/sysctl.conf /etc/sysctl.d/*
  register: cis_post_tmp
  changed_when: False
  tags:
    - post

- name: "POST | {{ cis_code }} - set post fact"
  set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_post":"{{ cis_post_tmp }}"}
  tags:
    - post

- name: "POST | {{ cis_code }} - print status"
  debug:
    var: cis_post_tmp
  tags:
    - post
    - debug

...
