---

# This file also covers:
# 1.1.7 Ensure separate partition exists for /var/tmp
# 1.1.8 Ensure nodev option set on  /var/tmp partition
# 1.1.9 Ensure nosuid option set on /var/tmp partition
# 1.1.10 Ensure noexec option set on /var/tmp partition

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.1.7'
    cis_name: &cis_name Ensure separate partition exists for /var/tmp
    cis_profile: &cis_profile level-2
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name }}"
  block:

  - name: "APPLY | {{ cis_code }} - create /var/tmp partition"
    parted:
      device: "{{ sdw }}"
      number: 1
      state: present
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - create ext4 filesystem on {{ sdw }}{{ part }} and check disk blocks"
    filesystem:
      fstype: ext4
      dev: "{{ sdw }}{{ part }}"
      #opts: -cc -O ^has_journal
      force: yes
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - data writeback"
    shell: |
      tune2fs -o journal_data_writeback {{ sdw }}{{ part }}
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - disable journal"
    shell: |
      tune2fs -O ^has_journal {{ sdw }}{{ part }}
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - require check"
    shell: |
      e2fsck -p -f {{ sdw }}{{ part }}
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - set label"
    shell: |
      e2label {{ sdw }}{{ part }} /var/tmp
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - dump filesystem options"
    shell: |
      dumpe2fs {{ sdw }}{{ part }}
    register: cis_apply_tmp
    tags:
      - apply
      - debug

  #- name: "APPLY| {{ cis_code }} - print filesystem options"
  #  debug:
  #    var: cis_apply_tmp
  #  tags:
  #    - apply
  #    - debug

  - name: "APPLY| {{ cis_code }} - setup /var/tmp permissions"
    shell: |
      mkdir -p /mnt/var_tmp
      mount -L /var/tmp /mnt/var_tmp
      chmod 1777 /mnt/var_tmp
      umount /mnt/var_tmp
      rm -rf /mnt/var_tmp
    tags:
      - apply

  # This prepares further cis /var/tmp checks
  - name: "APPLY | {{ cis_code }} - configure /var/tmp mount"
    mount:
      path: /var/tmp
      src: LABEL=/var/tmp
      fstype: ext4
      opts: auto,rw,nosuid,nodev,noexec,data=writeback,relatime
      state: present
    tags:
      - apply

  - import_tasks: ../commons/reboot-machine.yml
    vars:
      cis_code: *cis_code

  # TODO: Detailed fact
  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
    tags:
      - apply

  # TODO: Post checks

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
