---

# This file also covers
# 1.1.15 - Ensure nodev option set on /dev/shm partition
# 1.1.16 - Ensure nosuid option set on /dev/shm partition
# 1.1.17 - Ensure noexec option set on /dev/shm partition

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.1.15'
    cis_name: &cis_name Ensure nodev option set on /dev/shm partition
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name }}"
  block:

  - name: "APPLY | {{ cis_code }} - configure a separate mount point"
    mount:
      path: /dev/shm
      src: tmpfs
      fstype: tmpfs
      opts: defaults,nodev,nosuid,noexec
      dump: 0
      passno: 0
      state: present
    register: cis_apply_tmp
    tags:
      - apply

  - import_tasks: ../commons/reboot-machine.yml
    vars:
      cis_code: *cis_code

  # TODO: Detailed fact
  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
    tags:
      - apply

  # TODO: Post checks

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
