---

# This file also covers:
# 1.1.2 Ensure separate partition exists for /tmp
# 1.1.3 Ensure nodev option set on /tmp partition
# 1.1.4 Ensure nosuid option set on /tmp partition
# 1.1.5 Ensure noexec option set on /tmp partition

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.1.2'
    cis_name: &cis_name Ensure separate partition exists for /tmp
    cis_profile: &cis_profile level-2
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name }}"
  block:

  - import_tasks: ../commons/enable-package.yml
    vars:
      packages_to_enable:
      - parted
      cis_code: *cis_code

  - name: "APPLY | {{ cis_code }} - create /tmp partition"
    parted:
      device: "{{ sdt }}"
      number: 1
      state: present
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - create ext4 filesystem on {{ sdt }}{{ part }} and check disk blocks"
    filesystem:
      fstype: ext4
      dev: "{{ sdt }}{{ part }}"
      #opts: -cc -O ^has_journal
      force: yes
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - data writeback"
    shell: |
      tune2fs -o journal_data_writeback {{ sdt }}{{ part }}
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - disable journal"
    shell: |
      tune2fs -O ^has_journal {{ sdt }}{{ part }}
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - require check"
    shell: |
      e2fsck -p -f {{ sdt }}{{ part }}
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - set label"
    shell: |
      e2label {{ sdt }}{{ part }} /tmp
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - dump filesystem options"
    shell: |
      dumpe2fs {{ sdt }}{{ part }}
    register: cis_apply_tmp
    tags:
      - apply
      - debug

  #- name: "APPLY| {{ cis_code }} - print filesystem options"
  #  debug:
  #    var: cis_apply_tmp
  #  tags:
  #    - apply
  #    - debug

  - name: "APPLY| {{ cis_code }} - setup /tmp permissions"
    shell: |
      mkdir -p /mnt/tmp
      mount -L /tmp /mnt/tmp
      chmod 1777 /mnt/tmp
      umount /mnt/tmp
      rm -rf /mnt/tmp
    tags:
      - apply

  # This prepares further cis /tmp checks
  - name: "APPLY | {{ cis_code }} - configure /tmp mount"
    mount:
      path: /tmp
      src: LABEL=/tmp
      fstype: ext4
      opts: auto,rw,nosuid,nodev,noexec,data=writeback,noatime,nodiratime
      state: present
    tags:
      - apply

  - import_tasks: ../commons/reboot-machine.yml
    vars:
      cis_code: *cis_code

  # TODO: Detailed fact
  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
    tags:
      - apply

  # TODO: Post checks

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
