---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.1.11'
    cis_name: &cis_name Ensure separate partition exists for /var/log
    cis_profile: &cis_profile level-2
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name }}"
  block:

  - name: "APPLY | {{ cis_code }} - create /var/log partition"
    parted:
      device: "{{ sdl }}"
      number: 1
      state: present
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - create ext4 filesystem on {{ sdl }}{{ part }} and check disk blocks"
    filesystem:
      fstype: ext4
      dev: "{{ sdl }}{{ part }}"
      #opts: -cc -O ^has_journal
      force: yes
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - require check"
    shell: |
      e2fsck -p -f {{ sdl }}{{ part }}
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - set label"
    shell: |
      e2label {{ sdl }}{{ part }} /var/log
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - dump filesystem options"
    shell: |
      dumpe2fs {{ sdl }}{{ part }}
    register: cis_apply_tmp
    tags:
      - apply
      - debug

  #- name: "APPLY | {{ cis_code }} - print filesystem options"
  #  debug:
  #    var: cis_apply_tmp
  #  tags:
  #    - apply
  #    - debug

  - name: "APPLY | {{ cis_code }} - create mount point, assign permissions"
    file:
      path: /mnt/var_log
      state: directory
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - new filesystem mounted"
    mount:
      path: /mnt/var_log
      src: LABEL=/var/log
      state: mounted
      fstype: ext4
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - fix permissions on a new filesystem"
    file:
      path: /mnt/var_log
      state: directory
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - copy data to a new location"
    shell: |
      rsync --archive --xattrs --archive --hard-links --partial --one-file-system --progress /var/log/ /mnt/var_log
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - new filesystem unmounted"
    mount:
      path: /mnt/var_log
      state: unmounted
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - temporary mount point deleted"
    mount:
      path: /mnt/var_log
      state: absent
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - configure a separate mount point"
    mount:
      path: /var/log
      src: LABEL=/var/log
      fstype: ext4
      opts: defaults,relatime,data=ordered
      dump: 1
      passno: 1
      state: present
    tags:
      - apply

  - import_tasks: ../commons/reboot-machine.yml
    vars:
      cis_code: *cis_code

  # TODO: Determine what is going to be mounted in addition to /. Consider separate /var.
  - name: "APPLY | {{ cis_code }} - clean bind mount"
    shell: |
      mkdir -p /mnt/root
      mount --bind / /mnt/root
      rm -rf /mnt/root/var/log/*
      umount /mnt/root
      rmdir /mnt/root
    tags:
      - apply

  # TODO: Detailed fact
  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
    tags:
      - apply

  # TODO: Post checks

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
