---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.1.19'
    cis_name: &cis_name Disable Automounting
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name }}"
  block:

  - import_tasks: ../commons/disable-service.yml
    vars:
      services_to_disable:
      - autofs
      cis_code: *cis_code

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
