---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.4.1'
    cis_name: &cis_name Ensure permissions on bootloader config are configured
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name }}"
  block:

  - import_tasks: ../commons/configure-permissions.yml
    vars:
      path: "{{ grub_menu }}"
      owner: root
      group: root
      mode: og-rwx
      type: file
      cis_code: *cis_code
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
