---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.5.2'
    cis_name: &cis_name Ensure XD/NX support is enabled
    cis_section: &cis_section section-1
    cis_scored: &cis_scored scored
    cis_profile: &cis_profile level-1
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name }}"
  when:
    ansible_architecture == "x86_64"
  block:
  - import_tasks: ../commons/script-post.yml
    vars:
      cis_script: "{{ role_path }}/scripts/cis-1.5.02.sh"
      cis_code: *cis_code
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
