---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.5.4'
    cis_name: &cis_name Ensure prelink is disabled
    cis_profile: &cis_profile level-2
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name}}"
  block:

  # TODO: refactor to ansible modules
  - name: "APPLY | {{ cis_code }} - unlink if possible."
    shell: |
      prelink_path=$(/bin/env which prelink)
      if [[ "$?" -eq "0" ]]; then
        echo "do unlink: ${prelink_path} ..."
        ${prelink_path} --version
        ${prelink_path} --undo --all --verbose
      else
        echo 'no prelink found ...'
      fi
    register: cis_apply_tmp
    tags:
      - apply

  - import_tasks: ../commons/remove-package.yml
    vars:
      packages_to_remove:
      - prelink
      cis_code: *cis_code

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
