---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.5.1'
    cis_name: &cis_name Ensure core dumps are restricted
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored not_scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name }}"
  block:

  - import_tasks: ../commons/set-sysctl.yml
    vars:
      param: fs.suid_dumpable
      value: 0
      cis_code: *cis_code

  - name: "APPLY | {{ cis_code }} - update /etc/security/limits.conf"
    lineinfile:
      path: /etc/security/limits.conf
      regexp: '^\*\s+hard\s+core\s+.+$'
      line: "* hard core 0"
      state: present
      backup: 'no'
      backrefs: 'no'
      create: 'no'
      # Scan till the end
      firstmatch: 'no'
      # No validation available for /etc/security/limits.conf
      validate: '/bin/env true %s'
    register: cis_apply_tmp
    tags:
      - apply

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
