---

# TODO: This on should be set to enforcing later, when all the policies are ready.
# For the moment it's permissive

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.6.1.2'
    cis_name: &cis_name Ensure the SELinux state is permissive
    cis_profile: &cis_profile level-2
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - name: "APPLY | {{ cis_code }} - update configuration"
    lineinfile:
      path: /etc/selinux/config
      regexp: '^\s*SELINUX\s*=.*$'
      line: "SELINUX=permissive"
      state: present
      backup: 'no'
      backrefs: 'no'
      create: 'no'
      firstmatch: 'yes'
      # TODO: validation
      validate: '/bin/env true %s'
    register: cis_apply_tmp
    tags:
      - apply

  - import_tasks: ../commons/reboot-machine.yml
    vars:
      cis_code: *cis_code
    when: >-
      cis_apply_tmp is changed

  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
    tags:
      - apply

  - name: "POST | {{ cis_code }} - get current runtime values."
    shell: |
      sestatus
    failed_when: >-
      cis_post_tmp.rc != 0
      or not (cis_post_tmp.stdout is search('Current\s*mode:\s*permissive'))
      or not (cis_post_tmp.stdout is search('Mode\s*from\s*config\s*file:\s*permissive'))
      or cis_post_tmp.stderr|length>0
    changed_when: False
    register: cis_post_tmp
    tags:
      - post

  - name: "POST | {{ cis_code }} - get current config values."
    shell: |
      grep 'SELINUX=permissive' /etc/selinux/config
    failed_when: >-
      cis_post_tmp.rc != 0
      or not cis_post_tmp.stdout is search('SELINUX=permissive')
      or cis_post_tmp.stderr|length>0
    changed_when: False
    register: cis_post_tmp
    tags:
      - post

  - name: "POST | {{ cis_code }} - set post fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_post":"{{ cis_post_tmp }}"}
    tags:
      - post

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
