---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.6.1.3'
    cis_name: &cis_name Ensure SELinux policy is configured
    cis_profile: &cis_profile level-2
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - name: "APPLY | {{ cis_code }} - update configuration"
    lineinfile:
      path: /etc/selinux/config
      regexp: '^\s*SELINUXTYPE\s*=.*$'
      line: "SELINUXTYPE=targeted"
      state: present
      backup: 'no'
      backrefs: 'no'
      create: 'no'
      firstmatch: 'yes'
      # TODO: validation
      validate: '/bin/env true %s'
    register: cis_apply_tmp
    tags:
      - apply

  - import_tasks: ../commons/reboot-machine.yml
    vars:
      cis_code: *cis_code
    when: >-
      cis_apply_tmp is changed

  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
    tags:
      - apply

  - name: "POST | {{ cis_code }} - get current runtime values"
    shell: |
      sestatus
    failed_when: >-
      cis_post_tmp.rc!=0 or
      not (cis_post_tmp.stdout is search('Loaded\s*policy\s*name:\s*targeted')) or
      cis_post_tmp.stderr|length>0
    changed_when: False
    register: cis_post_tmp
    tags:
      - post

  - name: "POST | {{ cis_code }} - get current config values"
    shell: |
      grep 'SELINUXTYPE=targeted' /etc/selinux/config
    failed_when: >-
      cis_post_tmp.rc!=0
      or not(cis_post_tmp.stdout is search('SELINUXTYPE=targeted'))
      or cis_post_tmp.stderr|length>0
    changed_when: False
    register: cis_post_tmp
    tags:
      - post

  - name: "POST | {{ cis_code }} - set post fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_post":"{{ cis_post_tmp }}"}
    tags:
      - post

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
