---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.6.1.5'
    cis_name: &cis_name Ensure the MCS Translation Service (mcstrans) is not installed
    cis_profile: &cis_profile level-2
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:
  - import_tasks: ../commons/remove-package.yml
    vars:
      packages_to_remove:
      - mcstrans
      cis_code: *cis_code
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
