---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.7.1.8'
    cis_name: &cis_name Ensure permissions on /etc/issue are configured
    cis_profile: &cis_profile level-2
    cis_scored: &cis_scored not_scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:
  - import_tasks: ../commons/configure-permissions.yml
    vars:
      path: /etc/issue.net
      owner: root
      group: root
      mode: 0644
      type: file
      cis_code: *cis_code
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
