---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.7.1.2'
    cis_name: &cis_name Ensure message of the day is configured properly
    cis_profile: &cis_profile level-2
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - name: "APPLY | {{ cis_code }} - write file content."
    copy:
      content: "Authorized uses only. All activity may be monitored and reported."
      dest: "/etc/issue"
    register: cis_apply_tmp
    tags:
      - apply
    
  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
    tags:
      - apply
    
  - name: "POST | {{ cis_code }} - get file content"
    shell: |
      cat /etc/issue
      egrep '(\\v|\\r|\\m|\\s)' /etc/issue
    register: cis_post_tmp
    changed_when: False
    failed_when: False
    tags:
      - post
    
  - name: "POST | {{ cis_code }} - set post fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_post":"{{ cis_post_tmp }}"}
    tags:
      - post
    
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
