---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '1.8'
    cis_name: &cis_name Ensure updates, patches, and additional security software are installed
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored not_scored
    cis_section: &cis_section section-1
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - name: "APPLY | {{ cis_code }} - run updates."
    shell: |
      yum update --assumeyes
    register: cis_apply_tmp
    tags:
      - apply

  - import_tasks: ../commons/reboot-machine.yml
    vars:
      cis_code: *cis_code
    
  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
    tags:
      - apply
    
  - name: "POST | {{ cis_code }} - get package update information"
    shell: |
      yum check-update
    register: cis_post_tmp
    tags:
      - post
    
  - name: "POST | {{ cis_code }} - set post fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_post":"{{ cis_post_tmp }}"}
    tags:
      - post
    
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
