---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '2.2.1.2'
    cis_name: &cis_name Ensure ntp is configured
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-2
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - name: "APPLY | {{ cis_code }} - update -4 parameter"
    lineinfile:
      path: /etc/ntp.conf
      regexp: '^\s*restrict\s*\-4.*$'
      line: "restrict -4 default kod nomodify notrap nopeer noquery"
      state: present
      backup: 'no'
      backrefs: 'no'
      create: 'no'
      firstmatch: 'yes'
      # TODO: validation
      validate: '/bin/env true %s'
    register: cis_apply_tmp_dash_4
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - update -6 parameter"
    lineinfile:
      path: /etc/ntp.conf
      regexp: '^\s*restrict\s*\-6.*$'
      line: "restrict -6 default kod nomodify notrap nopeer noquery"
      state: present
      backup: 'no'
      backrefs: 'no'
      create: 'no'
      firstmatch: 'yes'
      # TODO: validation
      validate: '/bin/env true %s'
    register: cis_apply_tmp_dash_6
    tags:
      - apply

  # AWS Inspector Compliance
  - name: "APPLY | {{ cis_code }} - update daemon options"
    lineinfile:
      path: /etc/sysconfig/ntpd
      #regexp: '^\s*(#OPTIONS=")(.+)(")\s*$'
      line: '#OPTIONS=-g -u ntp:ntp'
      state: present
      backup: 'no'
      backrefs: 'no'
      create: 'no'
      firstmatch: 'yes'
      # TODO: validation
      validate: '/bin/env true %s'
    register: cis_apply_tmp_daemon
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - restart service"
    service:
      name: ntpd
      state: restarted
    register: cis_apply_tmp_restart
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - set apply fact"
    set_fact: 
      "cis_{{ cis_code | regex_replace('[.]','_') }}_apply":
        dash_4: "{{ cis_apply_tmp_dash_4 }}"
        dash_6: "{{ cis_apply_tmp_dash_6 }}"
        daemon: "{{ cis_apply_tmp_daemon }}"
        restart: "{{ cis_apply_tmp_restart }}"
      cis_apply_tmp_dash_4:
      cis_apply_tmp_dash_6:
      cis_apply_tmp_daemon:
      cis_apply_tmp_restart:
    tags:
      - apply

  - name: "POST | {{ cis_code }} - get restrictions"
    shell: |
      grep "^restrict" /etc/ntp.conf
    register: cis_post_tmp_restrictions
    failed_when: >-
      cis_post_tmp_restrictions.rc!=0 or
      not (cis_post_tmp_restrictions.stdout is search('restrict -4 default kod nomodify notrap nopeer noquery')) or
      not (cis_post_tmp_restrictions.stdout is search('restrict -6 default kod nomodify notrap nopeer noquery')) or
      cis_post_tmp_restrictions.stderr|length>0
    tags:
      - post

  - name: "POST | {{ cis_code }} - get servers"
    shell: |
      grep -E "^(server|pool)" /etc/ntp.conf
    register: cis_post_tmp_servers
    failed_when: >-
      cis_post_tmp_servers.rc!=0 or
      not ((cis_post_tmp_servers.stdout is search('server ')) or (cis_post_tmp.stdout is search('pool '))) or
      cis_post_tmp_servers.stderr|length>0
    tags:
      - post

  - name: "POST | {{ cis_code }} - get daemon options 1"
    shell: |
      grep "daemon" /etc/init.d/ntpd
    register: cis_post_tmp_daemon_1
    failed_when: >-
      cis_post_tmp_daemon_1.rc!=0 or
      not (cis_post_tmp_daemon_1.stdout is search('-u ntp:ntp')) or
      cis_post_tmp_daemon_1.stderr|length>0
    when:
      ansible_distribution_version not in ["(Karoo)", "7.6", "7.7"]
    tags:
      - post

  # AWS Inspector Compliance
  - name: "POST | {{ cis_code }} - get daemon options 2"
    shell: |
      grep "#OPTIONS" /etc/sysconfig/ntpd
    register: cis_post_tmp_daemon_2
    failed_when: >-
      cis_post_tmp_daemon_2.rc!=0 or
      not (cis_post_tmp_daemon_2.stdout is search('-u ntp:ntp')) or
      cis_post_tmp_daemon_2.stderr|length>0
    tags:
      - post

  - name: "POST | {{ cis_code }} - get runtime options"
    shell: |
      ps ax | grep ntpd | grep -v 'grep'
    register: cis_post_tmp_runtime
    failed_when: >-
      not (cis_post_tmp_runtime.stdout is search('-u ntp:ntp')) or
      cis_post_tmp_runtime.stderr|length>0
    tags:
      - post
# cis_post_tmp_runtime.rc!=0 or

  - name: "POST | {{ cis_code }} - set post fact"
    set_fact: 
      "cis_{{ cis_code | regex_replace('[.]','_') }}_post":
        restrictions: "{{ cis_post_tmp_restrictions }}"
        servers: "{{ cis_post_tmp_servers }}"
        daemon_1: "{{ cis_post_tmp_daemon_1 }}"
        daemon_2: "{{ cis_post_tmp_daemon_2 }}"
        runtime: "{{ cis_post_tmp_runtime }}"
      cis_post_tmp_restrictions:
      cis_post_tmp_servers:
      cis_post_tmp_daemon_1:
      cis_post_tmp_daemon_2:
      cis_post_tmp_runtime:
    tags:
      - post

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
