---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '2.2.1.1'
    cis_name: &cis_name Ensure time synchronization is in use
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored not_scored
    cis_section: &cis_section section-2
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - import_tasks: ../commons/enable-package.yml
    vars:
      packages_to_enable:
      - ntp
      # chrony conflicts with ntp-4.2.8p12-1.41.amzn1.x86_64
      #- chrony
      cis_code: *cis_code

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
