---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '2.3.3'
    cis_name: &cis_name Ensure talk client is not installed
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-2
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - import_tasks: ../commons/remove-package.yml
    vars:
      packages_to_remove:
      - talk
      cis_code: *cis_code

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
