---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '3.1.2'
    cis_name: &cis_name Ensure packet redirect sending is disabled
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-3
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - import_tasks: ../commons/set-sysctl.yml
    vars:
      param: net.ipv4.conf.all.send_redirects
      value: 0
      cis_code: *cis_code

  - import_tasks: ../commons/set-sysctl.yml
    vars:
      param: net.ipv4.conf.default.send_redirects
      value: 0
      cis_code: *cis_code

  - name: "APPLY | {{ cis_code }} - flash routes notified ..."
    debug:
      msg: "Notify flash routes ..."
    notify: Flush ipv4 route
    tags:
      - apply

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
