---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '3.4.1'
    cis_name: &cis_name Ensure TCP Wrappers is installed
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-3
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - import_tasks: ../commons/enable-package.yml
    vars:
      packages_to_enable:
      - tcp_wrappers
      cis_code: *cis_code

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
