---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '4.1.10'
    cis_name: &cis_name Ensure discretionary access control permission modification events are collected
    cis_profile: &cis_profile level-2
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-4
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name }}."
  block:

  - name: "CIS {{ cis_code }} - print server architecture."
    debug:
      var: ansible_architecture
    tags:
      - always

  - name: "CIS {{ cis_code }} - configure auditd rules."
    set_fact:
      auditd_rules:
        i386:
          - "-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>={{ uid }} -F auid!=4294967295"
          - "-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>={{ uid }} -F auid!=4294967295"
          - "-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>={{ uid }} -F auid!=4294967295"
        x86_64:
          - "-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>={{ uid }} -F auid!=4294967295"
          - "-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>={{ uid }} -F auid!=4294967295"
          - "-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>={{ uid }} -F auid!=4294967295"
          - "-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>={{ uid }} -F auid!=4294967295"
          - "-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>={{ uid }} -F auid!=4294967295"
          - "-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>={{ uid }} -F auid!=4294967295"
        aarch64:
          - "-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>={{ uid }} -F auid!=4294967295"
          - "-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>={{ uid }} -F auid!=4294967295"
          - "-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>={{ uid }} -F auid!=4294967295"
          - "-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>={{ uid }} -F auid!=4294967295"
    failed_when: "ansible_architecture not in auditd_rules"
    tags:
      - always

  - import_tasks: ../commons/set-auditd-rules.yml
    vars:
      filter: perm_mod
      rules: "{{ auditd_rules[ansible_architecture] }}"
      cis_code: *cis_code

  - name: "CIS {{ cis_code }} - clean rules configuration."
    set_fact:
      auditd_rules:
    tags:
      - always

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
