---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '4.1.17'
    cis_name: &cis_name Ensure kernel module loading and unloading is collected
    cis_profile: &cis_profile level-2
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-4
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name }}."
  block:

  - name: "CIS {{ cis_code }} - print server architecture."
    debug:
      var: ansible_architecture
    tags:
      - always

  - name: "CIS {{ cis_code }} - configure auditd rules."
    set_fact:
      auditd_rules:
        i386:
          - -w /sbin/insmod -p x
          - -w /sbin/rmmod -p x
          - -w /sbin/modprobe -p x
          - -a always,exit -F arch=b32 -S init_module -S delete_module
        x86_64:
          - -w /sbin/insmod -p x
          - -w /sbin/rmmod -p x
          - -w /sbin/modprobe -p x
          - -a always,exit -F arch=b64 -S init_module -S delete_module
        aarch64:
          - -w /sbin/insmod -p x
          - -w /sbin/rmmod -p x
          - -w /sbin/modprobe -p x
          - -a always,exit -F arch=b64 -S init_module -S delete_module
    failed_when: "ansible_architecture not in auditd_rules"
    tags:
      - always

  - import_tasks: ../commons/set-auditd-rules.yml
    vars:
      filter: modules
      rules: "{{ auditd_rules[ansible_architecture] }}"
      cis_code: *cis_code

  - name: "CIS {{ cis_code }} - clean rules configuration."
    set_fact:
      auditd_rules:
    tags:
      - always

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
