---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '4.1.3'
    cis_name: &cis_name Ensure auditing for processes that start prior to auditd is enabled
    cis_profile: &cis_profile level-2
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-4
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  # Debug: https://regex101.com/
  # Sample1: kernel /boot/vmlinuz-4.14.123-86.109.amzn1.x86_64 root=LABEL=/ console=tty1 audit=x console=ttyS0 nvme_core.io_timeout=4294967295
  # Sample2: kernel /boot/vmlinuz-4.14.123-86.109.amzn1.x86_64 root=LABEL=/ console=tty1 console=ttyS0 nvme_core.io_timeout=4294967295 audit=xxxx
  # Sample3: kernel /boot/vmlinuz-4.14.123-86.109.amzn1.x86_64 root=LABEL=/ console=tty1 console=ttyS0 nvme_core.io_timeout=4294967295
  # https://www.regular-expressions.info/lookaround.html
  # https://stackoverflow.com/questions/406230/regular-expression-to-match-a-line-that-doesnt-contain-a-word
  # Ansible replace is re.MULTILINE
  # Update option if any
  - name: "APPLY | {{ cis_code }} - update options."
    replace:
      path: "{{ grub_menu }}"
      regexp: "{{ item }}"
      replace: '\1audit=1\3'
      backup: 'no'
    with_items:
      - '({{ grub_kernel }}.*\s+)(audit=\S+)(\s+.+$)'
      - '({{ grub_kernel }}.*\s+)(audit=\S+)(\s+$)'
      - '({{ grub_kernel }}.*\s+)(audit=\S+)($)'
    register: cis_apply_tmp
    tags:
      - apply

  # Add an option to the end of kernel string
  - name: "APPLY | {{ cis_code }} - insert options."
    replace:
      path: "{{ grub_menu }}"
      regexp: '({{ grub_kernel }}((?!audit=\S+).)*)$'
      replace: '\1 audit=1'
      backup: 'no'
    register: cis_apply_tmp
    tags:
      - apply

  - import_tasks: ../commons/reboot-machine.yml
    vars:
      cis_code: *cis_code

  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
    tags:
      - apply

  - name: "POST | {{ cis_code }} - get kernel lines."
    shell: |
      grep -E '{{ grub_kernel }}' {{ grub_menu }}
    register: cis_post_tmp
    tags:
      - post

  - name: "POST | {{ cis_code }} - set post fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_post":"{{ cis_post_tmp }}"}
    tags:
      - post

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
