---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '4.1.1.2'
    cis_name: &cis_name Ensure system is disabled when audit logs are full
    cis_profile: &cis_profile level-2
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-4
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - name: "APPLY | {{ cis_code }} - update /etc/audit/auditd.conf"
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^\s*space_left_action\s*\=\s*.+$'
      line: "space_left_action = email"
      state: present
      backup: 'no'
      backrefs: 'no'
      create: 'no'
      # Scan till the end
      firstmatch: 'no'
      # No validation available for /etc/audit/auditd.conf
      validate: '/bin/env true %s'
    register: cis_apply_tmp
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - update /etc/audit/auditd.conf"
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^\s*action_mail_acct\s*\=\s*.+$'
      line: "action_mail_acct = root"
      state: present
      backup: 'no'
      backrefs: 'no'
      create: 'no'
      # Scan till the end
      firstmatch: 'no'
      # No validation available for /etc/audit/auditd.conf
      validate: '/bin/env true %s'
    register: cis_apply_tmp
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - update /etc/audit/auditd.conf"
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^\s*admin_space_left_action\s*\=\s*.+$'
      line: "admin_space_left_action = halt"
      state: present
      backup: 'no'
      backrefs: 'no'
      create: 'no'
      # Scan till the end
      firstmatch: 'no'
      # No validation available for /etc/audit/auditd.conf
      validate: '/bin/env true %s'
    register: cis_apply_tmp
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
    tags:
      - apply
    
  - name: "POST | {{ cis_code }} - get configuration info"
    shell: |
      grep space_left_action /etc/audit/auditd.conf
    register: cis_post_tmp
    failed_when: >-
      cis_post_tmp.rc!=0
      or cis_post_tmp.stderr_lines | length >0
    tags:
      - post

  - name: "POST | {{ cis_code }} - get configuration info"
    shell: |
      grep action_mail_acct /etc/audit/auditd.conf
    register: cis_post_tmp
    failed_when: >-
      cis_post_tmp.rc!=0
      or cis_post_tmp.stderr_lines | length >0
    tags:
      - post

  - name: "POST | {{ cis_code }} - get configuration info"
    shell: |
      grep admin_space_left_action /etc/audit/auditd.conf
    register: cis_post_tmp
    failed_when: >-
      cis_post_tmp.rc!=0
      or cis_post_tmp.stderr_lines | length >0
    tags:
      - post

  - name: "POST | {{ cis_code }} - set post fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_post":"{{ cis_post_tmp }}"}
    tags:
      - post
    
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
