---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '4.2.4'
    cis_name: &cis_name Ensure permissions on all logfiles are configured
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-4
  tags:
    - always

- block:

  - import_tasks: ../commons/script-apply.yml
    vars:
      cis_script: "{{ role_path }}/scripts/cis-4.2.04-apply.sh"
      cis_code: *cis_code

  #- import_tasks: ../commons/script-post.yml
  #  vars:
  #    cis_script: "{{ role_path }}/scripts/cis-4.2.04.sh"
  #    cis_code: *cis_code

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
