---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '5.1.8'
    cis_name: &cis_name Ensure at/cron is restricted to authorized users
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-5
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - name: "APPLY | {{ cis_code }} - remove *.deny files."
    file:
      path: "{{ item }}"
      state: absent
      recurse: 'no'
    with_items:
      - /etc/cron.deny
      - /etc/at.deny
    register: cis_apply_tmp
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - force *.allow files."
    file:
      path: "{{ item }}"
      owner: root
      group: root
      mode: 'og-rwx'
      state: touch
      recurse: 'no'
    with_items:
      - /etc/cron.allow
      - /etc/at.allow
    register: cis_apply_tmp
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
    tags:
      - apply
    
  - name: "POST | {{ cis_code }} - get files information"
    stat:
      path: "{{ item }}"
    with_items:
      - /etc/cron.deny
      - /etc/at.deny
      - /etc/cron.allow
      - /etc/at.allow
    changed_when: False
    failed_when: False
    register: cis_post_tmp
    tags:
      - post
    
  - name: "POST | {{ cis_code }} - set post fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_post":"{{ cis_post_tmp }}"}
    tags:
      - post
    
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
