---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '5.1.1'
    cis_name: &cis_name Ensure cron daemon is enabled
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-5
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name }}"
  block:
  - import_tasks: ../commons/enable-service.yml
    vars:
      services_to_enable:
      - crond
      cis_code: *cis_code
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
