---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '5.2.13'
    cis_name: &cis_name Ensure SSH Ciphers
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-5
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:
  - import_tasks: ../commons/set-sshd-parameter.yml
    vars:
      param: Ciphers
      value: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
      cis_code: *cis_code
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
