---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '5.2.14'
    cis_name: &cis_name Ensure SSH valid MACs list
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-5
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:
  - import_tasks: ../commons/set-sshd-parameter.yml
    vars:
      param: MACs
      value: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"
      cis_code: *cis_code
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
