---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '5.2.12'
    cis_name: &cis_name Ensure SSH Idle Timeout Interval is configured
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-5
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - import_tasks: ../commons/set-sshd-parameter.yml
    vars:
      param: ClientAliveInterval
      value: 300
      cis_code: *cis_code

  - import_tasks: ../commons/set-sshd-parameter.yml
    vars:
      param: ClientAliveCountMax
      value: 0
      cis_code: *cis_code

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
