---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '5.3.3'
    cis_name: &cis_name Ensure password reuse is limited
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-5
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - name: "APPLY | {{ cis_code }} - configure files"
    set_fact:
      files:
        - /etc/pam.d/password-auth
        - /etc/pam.d/system-auth
      days: 5
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - update pam configuraion files."
    lineinfile:
      path: "{{ item }}"
      regexp: '^\s*password\s+required\s+pam_pwhistory.so\s+remember=5\s*$'
      line: "password required pam_pwhistory.so remember={{ days }}"
      state: present
      backup: 'no'
      backrefs: 'no'
      create: 'no'
      insertbefore: '^password\s*sufficient\s*pam_unix\.so\s+.*$'
      firstmatch: 'no'
      validate: '/bin/env true %s'
    with_items: "{{ files }}"
    register: cis_apply_tmp
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: 
      "cis_{{ cis_code | regex_replace('[.]','_') }}_apply": "{{ cis_apply_tmp }}"
      files:
      days:
      cis_apply_tmp:
    tags:
      - apply
    
    # TODO: Test days number
  - name: "POST | {{ cis_code }} - get configuration info"
    shell: |
      egrep '^password\s+required\s+pam_pwhistory.so' {{ item }}
    with_items:
      - /etc/pam.d/password-auth
      - /etc/pam.d/system-auth
    register: cis_post_tmp
    failed_when: >-
      cis_post_tmp.rc!=0
      or cis_post_tmp.stderr_lines | length >0
      or not (cis_post_tmp.stdout is search('remember=' ~ 5))
    changed_when: False
    tags:
      - post

  - name: "POST | {{ cis_code }} - set post fact."
    set_fact: 
      "cis_{{ cis_code | regex_replace('[.]','_') }}_post": "{{ cis_post_tmp }}"
      cis_post_tmp:
    tags:
      - post
    
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
