---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '5.4.4'
    cis_name: &cis_name Ensure default user umask is 027 or more restrictive
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-5
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - name: "APPLY | {{ cis_code }} - update umask."
    replace:
      path: "{{ item.path }}"
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
    with_items:
      - {path: '/etc/profile', regexp: '^(\s*)(umask\s*022)(\s*)$', replace: '\1umask 027\3'}
      - {path: '/etc/profile', regexp: '^(\s*)(umask\s*002)(\s*)$', replace: '\1umask 027\3'}
      - {path: '/etc/bashrc', regexp: '^(\s*)(umask\s*022)(\s*)$', replace: '\1umask 027\3'}
      - {path: '/etc/bashrc', regexp: '^(\s*)(umask\s*002)(\s*)$', replace: '\1umask 027\3'}
    register: cis_apply_tmp
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
    tags:
      - apply

  - name: "POST | {{ cis_code }} - find loose umasks"
    shell: |
      grep "umask" /etc/bashrc /etc/profile /etc/profile.d/*.sh
    register: cis_post_tmp
    changed_when: False
    failed_when: >-
      cis_post_tmp.rc!=0 or
      cis_post_tmp.stdout is search('umask 000') or
      cis_post_tmp.stdout is search('umask 002') or
      cis_post_tmp.stdout is search('umask 007') or
      cis_post_tmp.stdout is search('umask 022') or
      cis_post_tmp.stderr|length>0
    tags:
      - post

  - name: "POST | {{ cis_code }} - set post fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_post":"{{ cis_post_tmp }}"}
    tags:
      - post

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
