---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '5.4.1.4'
    cis_name: &cis_name Ensure inactive password lock is 30 days or less
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-5
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - name: "APPLY | {{ cis_code }} - get default inactive interval"
    shell: |
      useradd -D | grep INACTIVE | head --lines 1 --silent | tr --delete [:space:] | cut -d'=' -f2 | tr --delete [:space:]
    register: cis_apply_tmp_01
    failed_when: >-
      cis_apply_tmp_01.rc!=0
      or cis_apply_tmp_01.stderr_lines | length >0
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - update default inactive interval"
    shell: |
      useradd -D -f 30
    register: cis_apply_tmp_02
    failed_when: >-
      cis_apply_tmp_02.rc!=0
      or cis_apply_tmp_02.stderr_lines | length >0
    when: >-
      cis_apply_tmp_01.stdout | int > 30
      or cis_apply_tmp_01.stdout | int <= 0
    tags:
      - apply

  - import_tasks: ../commons/script-apply.yml
    vars:
      cis_script: "{{ role_path }}/scripts/cis-5.4.01.4-apply.sh"
      cis_code: *cis_code

  - name: "POST | {{ cis_code }} - get current inactive interval"
    shell: |
      useradd -D | grep INACTIVE | head --lines 1 --silent | tr --delete [:space:] | cut -d'=' -f2 | tr --delete [:space:]
    register: cis_post_tmp
    failed_when: >-
      cis_post_tmp.rc!=0
      or cis_post_tmp.stderr_lines | length >0
      or cis_post_tmp.stdout | int >30
      or cis_post_tmp.stdout | int <=0
    changed_when: False
    tags:
      - apply

  - import_tasks: ../commons/script-post.yml
    vars:
      cis_script: "{{ role_path }}/scripts/cis-5.4.01.4.sh"
      cis_code: *cis_code

  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
