---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '5.5'
    cis_name: &cis_name Ensure access to the su command is restricted
    cis_profile: &cis_profile level-1
    cis_scored: &cis_scored scored
    cis_section: &cis_section section-5
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - name: "APPLY | {{ cis_code }} - update /etc/pam.d/su."
    lineinfile:
      path: /etc/pam.d/su
      regexp: '^\s*[#]*\s*auth\s+required\s+pam_wheel.so\s+use_uid\s*$'
      line: "auth\t\trequired\tpam_wheel.so use_uid"
      state: present
      backup: 'no'
      backrefs: 'no'
      create: 'no'
      # Scan till the end
      firstmatch: 'no'
      # No validation available for /etc/pam.d/su
      validate: '/bin/env true %s'
    register: cis_apply_tmp
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{{ cis_apply_tmp }}"}
    tags:
      - apply
    
  - name: "POST | {{ cis_code }} - get configuration info"
    shell: |
      grep wheel /etc/group
    register: cis_post_tmp
    failed_when: >-
      cis_post_tmp.rc!=0
      or cis_post_tmp.stderr_lines | length >0
    tags:
      - post

  - name: "POST | {{ cis_code }} - get configuration info"
    shell: |
      grep pam_wheel.so /etc/pam.d/su
    register: cis_post_tmp
    failed_when: >-
      cis_post_tmp.rc!=0
      or cis_post_tmp.stderr_lines | length >0
    tags:
      - post
    
  - name: "POST | {{ cis_code }} - set post fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_post":"{{ cis_post_tmp }}"}
    tags:
      - post
    
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
