---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '6.2.3'
    cis_name: &cis_name Ensure no legacy "+" entries exist in /etc/shadow
    cis_section: &cis_section section-6
    cis_scored: &cis_scored scored
    cis_profile: &cis_profile level-1
  tags:
    - always

- name: CIS {{ cis_code }} - {{ cis_name }}
  block:

  - name: "APPLY | {{ cis_code }} - remove plus lines."
    replace:
      backup: 'no'
      path: /etc/shadow
      regexp: '^(\s*\+[^:]*\s*):.+$'
      #validate: /usr/sbin/pwck -r -q /etc/passwd %s
    register: cis_apply_tmp_01
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - remove blank lines."
    shell: |
     sed -e '/^\s*$/d' -i /etc/shadow
    args:
      warn: false
    register: cis_apply_tmp_02
    tags:
      - apply

  - name: "APPLY | {{ cis_code }} - set apply fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_apply":"{ lines: {{ cis_apply_tmp_01 }}, blanks: {{ cis_apply_tmp_02 }} }"}
    tags:
      - apply
    
  - name: "POST | {{ cis_code }} - test plus lines absense (per doc)."
    shell: |
      grep '^\+:' /etc/shadow
    failed_when: >-
      cis_post_tmp.rc!=1 or
      cis_post_tmp.stderr_lines | length >0 or
      cis_post_tmp.stdout_lines | length >0
    changed_when: False
    register: cis_post_tmp
    tags:
      - post

  - name: "POST | {{ cis_code }} - test plus lines absense (all entries)."
    shell:
      grep '^\s*\+[^:]+\s*:' /etc/shadow
    failed_when: >-
      cis_post_tmp.rc!=1 or
      cis_post_tmp.stderr_lines | length >0 or
      cis_post_tmp.stdout_lines | length >0
    changed_when: False
    register: cis_post_tmp
    tags:
      - post

  - name: "POST | {{ cis_code }} - test /etc/shadow validity."
    shell: |
     #/usr/sbin/pwck -r -q /etc/passwd /etc/shadow
    failed_when: cis_post_tmp.rc!=0
    changed_when: False
    register: cis_post_tmp
    tags:
      - apply
    
  - name: "POST | {{ cis_code }} - set post fact."
    set_fact: {"cis_{{ cis_code | regex_replace('[.]','_') }}_post":"{{ cis_post_tmp }}"}
    tags:
      - post

  - name: "POST | {{ cis_code }} - print post fact."
    debug:
      var: "cis_{{ cis_code | regex_replace('[.]','_') }}_post"
    tags:
      - post
      - debug
    
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
