---

- name: Set check facts
  set_fact:
    cis_code: &cis_code '6.2.5'
    cis_name: &cis_name Ensure root is the only UID 0 account
    cis_section: &cis_section section-6
    cis_scored: &cis_scored scored
    cis_profile: &cis_profile level-1
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name }}"
  block:
  - import_tasks: ../commons/script-post.yml
    vars:
      cis_script: "{{ role_path }}/scripts/cis-6.2.05.sh"
      cis_code: *cis_code
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
