---

# TODO: user lock like this 'passwd -l <username>'.

- name: Set check facts
  set_fact:
    cis_code: &cis_code '6.2.1'
    cis_name: &cis_name Ensure password fields are not empty
    cis_section: &cis_section section-6
    cis_scored: &cis_scored scored
    cis_profile: &cis_profile level-1
  tags:
    - always

- name: "CIS {{ cis_code }} - {{ cis_name }}"
  block:
  - import_tasks: ../commons/script-post.yml
    vars:
      cis_script: "{{ role_path }}/scripts/cis-6.2.01.sh"
      cis_code: *cis_code
  tags:
    - *cis_profile
    - *cis_section
    - *cis_code
    - *cis_scored

...
