---

# Postfilght tasks

- name: "POSTFLIGHT | save package report for CIS 1.6.1.6"
  become: no
  local_action:
    module: copy
    content: "{{ cis_1_6_1_6_post | default('MISSING DATA') | to_nice_json }}"
    dest: "{{ report_dir }}/unconfined-daemons.txt"
  tags:
    - '1.6.1.6'
    - post

- name: "POSTFLIGHT | save package report for CIS 6.1.1"
  become: no
  local_action:
    module: copy
    content: "{{ cis_6_1_1_post | default('MISSING DATA') | to_nice_json }}"
    dest: "{{ report_dir }}/packages.txt"
  tags:
    - '6.1.1'
    - post

- name: "POSTFLIGHT | save SUID report for CIS 6.1.13"
  become: no
  local_action:
    module: copy
    content: "{{ cis_6_1_13_post | default('MISSING DATA') | to_nice_json }}"
    dest: "{{ report_dir }}/suid-files.txt"
  tags:
    - '6.1.13'
    - post

- name: "POSTFLIGHT | save SGID report for CIS 6.1.14"
  become: no
  local_action:
    module: copy
    content: "{{ cis_6_1_14_post | default('MISSING DATA') | to_nice_json }}"
    dest: "{{ report_dir }}/sgid-files.txt"
  tags:
    - '6.1.14'
    - post

- name: "POSTFLIGHT | save files"
  fetch:
    src: "{{ item }}"
    dest: "{{ report_dir }}{{ item }}"
    flat: yes
    fail_on_missing: no
  # Absolute pathes. Leading slash is mandatory.
  with_items:
    - /etc/pam.d/password-auth
    - /etc/pam.d/system-auth
    - /etc/fstab
    - /etc/pam.d/su
    - "{{ grub_menu }}"
    - /etc/selinux/config
    - /etc/sysctl.conf
    - /etc/sysconfig/ntpd
    - /etc/ntp.conf
  tags:
    - always

- name: "POSTFLIGHT | collect information"
  shell: "{{ item }}"
  args:
    warn: False
  with_items:
    - uptime
    - mount
    - 'chkconfig --list'
    - 'netstat --all --numeric | grep LISTEN'
    - sestatus
    - 'sysctl -a'
    # Priviledged programs
    - 'find / -xdev \( -perm -4000 -o -perm -2000 \) -type f'
    - 'crontab -l -u root; exit 0'
  register: postflight_result
  changed_when: False
  tags:
    - always

- name: "POSTFLIGHT | save collected information"
  become: no
  local_action:
    module: copy
    content: "{{ postflight_result | to_nice_json }}"
    dest: "{{ report_dir }}/info.txt"
  tags:
    - always

- name: "POSTFLIGHT | save ansible facts"
  become: no
  local_action:
    module: copy
    content: "{{ ansible_facts | to_nice_json }}"
    dest: "{{ report_dir }}/ansible_facts.json"
  tags:
    - always

- name: "POSTFLIGHT | save ansible facts"
  become: no
  debug:
    msg: "Report dir is: {{ report_dir }}"
  tags:
    - always

...
