---

# Preflight tasks

- name: "PREFLIGHT | check 001"
  fail:
    msg: ansible_distribution is not defined
  when: ansible_distribution is not defined
  tags:
    - always

- name: "PREFLIGHT | check 002"
  fail:
    msg: ansible_distribution_version is not defined
  when: ansible_distribution_version is not defined
  tags:
    - always

- name: "PREFLIGHT | check 003"
  fail:
    msg: ansible_architecture is not defined
  when: ansible_architecture is not defined
  tags:
    - always

- name: "PREFLIGHT | information printed"
  debug:
    msg: |
      Distribution: {{ ansible_distribution }}
      Version: {{ ansible_distribution_version }}
      Architecture: {{ ansible_architecture }}
  tags:
    - always

- name: "PREFLIGHT | generate play uuid"
  set_fact:
    play_uuid: "{{ (999999999999999999999 | random | string + (lookup('pipe', 'date +%s%N'))) | to_uuid() }}"
  tags:
    - always

- name: "PREFLIGHT | generate play report dir"
  set_fact:
    report_dir: "{{ lookup('env', 'PWD') }}/.report/{{ play_uuid }}"
  tags:
    - always

- name: "PREFLIGHT | ansible create directory example."
  become: no
  local_action:
    module: file
    path: "{{ report_dir }}"
    state: directory
    mode: 'u=rwx,g=rx,o='
  tags:
    - always

...
